// Generated by CoffeeScript 1.6.3
var stroke;

stroke = require('../chinese-stroke');

exports.stroke_test = {
  success: function(test) {
    test.expect(1);
    test.equals(stroke.get('好') === 6, true);
    return test.done();
  }
};
